# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TestSwiftUI' do
	pod 'UIColor_Hex_Swift'
end

target 'TestSwiftUITests' do

end

target 'TestSwiftUIUITests' do

end

